language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly


before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - if [ ! -d "apache-cassandra-3.9" ]; then wget http://www.us.apache.org/dist/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz && tar -xvzf apache-cassandra-3.9-bin.tar.gz; fi
  - sudo sh ./apache-cassandra-3.9/bin/cassandra -R
  - sleep 20


install:
  - (cargo install rustfmt --force  || true)
  - PATH=$PATH:/home/travis/.cargo/bin

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose

addons:
  apt:
    packages:
      - kcov
      - oracle-java8-installer



after_success:
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/<executable name>-* &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
